### ISSUE TITLE
Draft our own code of conduct for all Casbin projects

### ISSUE THREAD

**Issue by hsluoyz** [casbin/code-of-conduct#1]
Some examples:

- Docker: https://github.com/docker/code-of-conduct/blob/master/code-of-conduct-EN.md
- Microsoft: https://microsoft.github.io/codeofconduct/
- Angular: https://github.com/angular/code-of-conduct
...

GitHub docs: https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project

**Comment by hsluoyz** [comment]
@nodece @GopherJ @xcaptain @techoner @dovics @psiACE can anyone make a draft (PR) for it?

**Comment by PsiACE** [comment]
please check #2

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/code-of-conduct/pull/2
